INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (1, 'Moda', 1, null);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (2, 'Elektronik', 1, null);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (3, 'Ev & Yaşam', 1, null);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (4, 'Elbise', 2, 1);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (5, 'Gömlek', 2, 1);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (6, 'Bilgisayar', 2, 2);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (7, 'Dizüstü Bilgisayar', 3, 6);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (8, 'Mobilya', 2, 3);
INSERT INTO public.CATEGORY(ID, NAME, DEPTH, ID_TOP_CATEGORY)
VALUES (9, 'Sehpa', 3, 8);