INSERT INTO public.PRODUCT_COMMENT(ID, COMMENT, COMMENT_DATE, USER_ID, PRODUCT_ID)
VALUES (1, 'Harika tavsiye edilir', now(), 1, 4);
INSERT INTO public.PRODUCT_COMMENT(ID, COMMENT, COMMENT_DATE, USER_ID, PRODUCT_ID)
VALUES (2, 'Guzel', now(), 1, 3);
INSERT INTO public.PRODUCT_COMMENT(ID, COMMENT, COMMENT_DATE, USER_ID, PRODUCT_ID)
VALUES (3, 'Begendim', now(), 2, 3);
INSERT INTO public.PRODUCT_COMMENT(ID, COMMENT, COMMENT_DATE, USER_ID, PRODUCT_ID)
VALUES (4, 'Sevdim', now(), 3, 2);
INSERT INTO public.PRODUCT_COMMENT(ID, COMMENT, COMMENT_DATE, USER_ID, PRODUCT_ID)
VALUES (5, 'Tavsiye edilir', now(), 4, 4);