INSERT INTO public.URUN_YORUM(ID, YORUM, YORUM_TARIHI, KULLANICI_ID, URUN_ID)
VALUES (1, 'Harika tavsiye edilir', now(), 1, 4);
INSERT INTO public.URUN_YORUM(ID, YORUM, YORUM_TARIHI, KULLANICI_ID, URUN_ID)
VALUES (2, 'Guzel', now(), 1, 3);
INSERT INTO public.URUN_YORUM(ID, YORUM, YORUM_TARIHI, KULLANICI_ID, URUN_ID)
VALUES (3, 'Begendim', now(), 2, 3);
INSERT INTO public.URUN_YORUM(ID, YORUM, YORUM_TARIHI, KULLANICI_ID, URUN_ID)
VALUES (4, 'Sevdim', now(), 3, 2);
INSERT INTO public.URUN_YORUM(ID, YORUM, YORUM_TARIHI, KULLANICI_ID, URUN_ID)
VALUES (5, 'Tavsiye edilir', now(), 4, 4);